### ISSUE TITLE
UIDatePicker minuteInterval error

### ISSUE THREAD

**Issue by transitmark** [Raizlabs/Eject#24]
When a UIDatePicker is created the minuteInterval is incorrect.  It should be in Int.

> open var minuteInterval: Int // display minutes wheel with interval. interval must be evenly divided into 60. default is 1. min is 1, max is 30

let timePicker = UIDatePicker()
timePicker.datePickerMode = .dateAndTime
**timePicker.minuteInterval = .1**
timePicker.translatesAutoresizingMaskIntoConstraints = false

**Comment by SquaredTiki** [comment]
Just submitted a PR to fix this, see #25. Only a small change.

**Comment by KingOfBrian** [comment]
Merged in the PR -- website should be updated in a few! Thanks @smartcop and @SquaredTiki !
